name: Flow
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 355
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup
        run: chmod +x ./init.sh && ./init.sh
        env: 
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
