name: Flow
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Init
        run: chmod +x ./init.sh && ./init.sh

      - name: Setup
        uses: joshlarsen/ssh-tunnel-action@main
        with:
          timeout: 3h
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          ngrok_token: ${{ secrets.NGROK_TOKEN }}
