name: Snow
on: [workflow_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: mac-latest
    timeout-minutes: 330
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup
        run: chmod +x ./init-mac.sh && ./init-mac.sh
        env: 
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
