name: Water
on: [workflow_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup
        run: |
          chmod +x ./clean.sh && mv clean.sh $HOME/clean.sh;
          chmod +x ./init.sh && ./init.sh; 
        env: 
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
